language: python
sudo: true
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

deploy:
    provider: script
    script: bash ci/deploy.sh
    on:
        branch: master
