language: python
sudo: true
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose run app sh -c "pytest test.py -p no:cacheprovider"

deploy:
    provider: script
    script: bash ci/deploy.sh
    on:
        branch: master
